version: "3.8"
services:
  courses:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      JWT_SECRET: dasldjh4h1jk4kadhasdsa
      MONGO_URI: mongodb://mongo-db:27017/courses
      NODE_ENV: dev
      AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
      AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
      AWS_BUCKET: uomlms
      KAFKA_URL: "kafka:9092"
      KAFKA_GROUP_ID: "courses-group"
    depends_on:
      - mongo-db
      - kafka
  mongo-db:
    image: mongo
    ports: 
      - 27017:27017
    volumes:
      - .mongo:/data/db
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  zookeeper:
    image: bitnami/zookeeper:latest
    ports: 
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes